#!/bin/bash

# Calculates the S score for the presence-richness of the samples
# The sscore is the mean of the normalized presence and abundance of the gene

input_file=$1

info=$(awk '{
    for(i = 2; i <= 3; i++)
    { 
        sums[i] += $i
        sums_squared[i] += ($i)^2
    }
}
END {
    for(i = 2; i <= 3; i++)
    { 
        means[i - 1] = sums[i] / NR;
        std_devs[i - 1]=sqrt((sums_squared[i]-sums[i]^2/NR)/NR)
    }
    printf "%s,%s,%s,%s", means[1],std_devs[1],means[2],std_devs[2] 
}' $input_file)

awk -v var=$info '
BEGIN{
    split(var, info, ",")
    OFS="\t"
}
{  
    nR = ($2 - info[1]) / info[2] 
    nA = ($3 - info[3]) / info[4]
    nS = (nA + nR) / 2
    print $1 OFS $2 OFS $3 OFS substr(nS, 1, 5)
}' $input_file
