#!/usr/bin/python
"""
Quantifies the presence of the genes within a directory of *.m8 files.
The presence of a gene is how many samples a gene appears in.

Usage:
    count_presence dir

Inputs:
    - dir, a directory of .m8 files

Outputs:
    - two tab-separated columns of gene name and its presence
"""

import sys
import glob
import os

def main():
    all_dict = {}
    all_gene = {}
    input_dir = sys.argv[1]
    results_file_list = glob.glob("{}/*.m8".format(input_dir))
    for results_file in results_file_list:
        current_dict ={}
        if os.path.getsize(results_file) > 0:
            prev = ""
            with open(results_file) as fin:
                for line in open(results_file,'r'):
                    line = line.strip().split('\t')
                    if prev == line[0]:
                        continue
                    else:
                        prev = line[0]
                    current_dict[line[1]] = current_dict.get(line[1],0) + 1
                    # Initialize gene in the all_gene dictionary
                    all_gene[line[1]] = 0
        all_dict[results_file] = current_dict


    for item in all_dict.items():
        for gene in item[1].items():
            all_gene[gene[0]] += 1


    for item in all_gene.items():
        print("{}\t{}".format(item[0], str(item[1])))

if __name__ == '__main__':
    main()
	
