#!/bin/bash

input_file=$1
info=$(awk '{
    if(NR==1)
    {
        min = $3
        max = $3
    }
    if($3 < min)
    {
        min = $3
    }
     
}
END {
    print min","max
}' $input_file)

awk -v var=$info '
BEGIN {
    split(var, info, ",")
    min = info[1]
    max = info[2]
    OFS = "\t"
} 
{
    left = (max - $3) / NR;
    NR==20 ? right = 0: right = ($3 - min) / (20 - NR) 
    print $0 OFS left - right

}' $input_file
