#!/bin/bash

# Header used in various parts of the MFP tool set.

cat << EOF
#!/bin/bash

##### Resources Requested ##########
#SBATCH --time=4:00:00            
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=16G
#SBATCH --output=$1.out 
#SBATCH --error=$1.err

########## Command Lines to Run ##########

update_job_status $1 "Started \$(date +'%H:%M %m\/%d\/%y')"


EOF
