#!/bin/bash

# Header used in various parts of the MFP tool set.

cat << EOF
#!/bin/bash

##### Resources Requested ##########
#SBATCH --time=48:00:00            
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --mem-per-cpu=16G

########## Command Lines to Run ##########

update_job_status $1 "Started \$(date +'%H:%M %m\/%d\/%y')"

cat << EOF | /mnt/research/germs/softwares/parallel-20181022/src/parallel
EOF
